cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://www.erudio.com.br

file:
  upload-dir: /Documents/programs/doc


spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: 15032002
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB

    open-in-view: false
#para adicionar/configurar level de logs
logging:
  level:
    #root: WARN -> Define o tipo de nivel de toda a aplicacao(caso nao coloque o padrao e info)
    br.com.bthirtyeight: DEBUG #defini que os arquivos desse pacote sera usado em um tipo de nivel

#config personalizada para swagger
#essa config define q o swagger vai documentar a penas a classe controller que corresponde a esse path
spring-doc:    #/api/controler/v1/parametro de endpoint
  paths-to-match: /**/v1/**
  swagger-ui:
    use-root-path: true #define que ira utilizar a url base da aplicacao